### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/GSA_Toolkit#204]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Elements\Bar.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Elements\FEMesh.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Elements\Node.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Elements\RigidLink.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Properties\LinkConstraint.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Properties\Material.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Properties\SectionProperty.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\FromGsa\Properties\SurfaceProperty.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Group.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Elements\Bar.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Elements\FEMesh.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Elements\RigidLink.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Loads\LoadCombination.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Properties\SectionProperty.cs

 - [ ] GSA_Toolkit\GSA_Adapter\Convert\ToGsa\Properties\SurfaceProperties.cs

 - [ ] GSA_Toolkit\GSA_Adapter\CRUD\Create.cs

 - [ ] GSA_Toolkit\GSA_Adapter\CRUD\Read.cs

 - [ ] GSA_Toolkit\GSA_Adapter\CRUD\ReadResultsElements.cs

 - [ ] GSA_Toolkit\GSA_Adapter\CRUD\Update.cs

</p>
</details>

**Comment by IsakNaslundBh** [comment]
Reopening as not fully closed by the PR
