### ISSUE TITLE
GSA_Toolkit: Some Interface method do not cover all the types

### ISSUE THREAD

**Issue by adecler** [BHoM/GSA_Toolkit#48]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Closing this awaiting new compliance issues by @FraserGreenroyd from new CI checks
