### ISSUE TITLE
GSA_Test - Relative file path to GSA test file

### ISSUE THREAD

**Issue by njsmithies** [BHoM/GSA_Toolkit#56]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Closing this as related to now deleted GSA_Test project
